#!/bin/bash
# shellcheck disable=SC2120

# TODO(improvements): 
#    - Use 'install' instead of 'cp' for copying binaries
#   - Add more defense (maybe)?
#       - SELinux/AppArmor/Seccomp
#       - iptables/nftables rule to restrict jailed user to SSH only to certain hosts
#   - Use readonly bind mount?

# TODO(feat): 
#   - Set up fail2ban (different script?)
#   - Set up monitoring stack (different script?)

declare CHROOT_DIR='/var/chroot'
declare JAILED_USER='juvie'
declare BASTION_HOST_IP='192.168.4.95'
declare BASTION_SCRIPT='bastion.sh'
declare DESTINATIONS_OUTPUT_FILE="$CHROOT_DIR/destinations.txt"
declare SSH_CONFIG_FILE="$HOME/.ssh/config"

declare -a BINARIES=(
    "rbash"
    "ssh"
    "ping"
    "logger"
)

declare -a SYSTEM_FILES=(
    "/etc/passwd"
    "/etc/group"
    "/etc/nsswitch.conf"
    "/etc/hosts"
)

declare -a CHAR_SPECIAL_FILES=(
    "/dev/null"
    "/dev/tty" 
    "/dev/zero"
    "/dev/random"
    "/dev/urandom"
)

declare -a SYSTEM_DIRS=(
    "bin"
    "lib"
    "lib64"
    "dev"
    "etc"
    "etc/ssh"
    "home"
    "usr/bin"
    "lib/x86_64-linux-gnu"
)

declare VERBOSE=0

debug() {
    [[ $VERBOSE -gt 0 ]] && printf "[\033[33m DEBUG \033[0m]: %s\n" "$@"
}

err() {
    if [[ $# -gt 0 ]]; then
        printf >&2 "[\033[31m ERROR \033[0m]: "
        printf >&2 "%s\n" "$*"
    fi
}



while [[ -n $1 ]]; do
    case $1 in
        -c|--chroot-dir)
            { [[ -n $2 && ! $2 =~ ^- ]] && shift && CHROOT_DIR=$1; } || {
                err; printf >&2 "The -c/--chroot-dir option was given with no valid argument.\n"
                exit 1
            }
            printf "Chroot directory set to: %s\n" "$CHROOT_DIR"
            shift
            ;;
        -u|--jailed-user)
            { [[ -n $2 && ! $2 =~ ^- ]] && shift && JAILED_USER=$1; } || {
                err; printf >&2 "The -u/--jailed-user option was given with no valid argument.\n"
                exit 1
            }
            printf "Jailed user set to: %s\n" "$JAILED_USER"
            shift
            ;;
        -v|--verbose)
            VERBOSE=1
            shift;
            ;;
        -s|--bastion-script)
            { [[ -n $2 && ! $2 =~ ^-  ]] && shift && BASTION_SCRIPT=$1; } || {
                err; printf >&2 "No valid argument passed to -s/--script\n"; }
            shift;
            ;;
        -S|--ssh-config-file)
            { [[ -n $2 && ! $2 =~ ^- ]] && shift && SSH_CONFIG_FILE=$1; } || {
                err; printf >&2 "The --ssh-config-file option was given but no argument was specified.\n"
            }
            shift;
            ;;

        -h|--help)
            cat <<EOF
Usage: ${BASH_SOURCE[0]} [OPTIONS]

Automates the creation of a chroot jail and SSH-based bastion host.

Options:
  -c, --chroot-dir <DIR>         Specify the chroot jail directory (default: /var/chroot)
  -u, --jailed-user <USER>       Username to create inside the chroot jail (default: juvie)
  -v, --verbose                  Enable verbose debug output
  -s, --bastion-script <SCRIPT>  Path to the custom bastion shell script to install (default: ./bastion.sh)
  -S, --ssh-config-file <FILE>   Path to SSH config file to parse for destination targets (default: ~/.ssh/config)
  -h, --help                     Show this help message and exit

This script sets up:
  - A jailed user account with chroot restrictions
  - A restricted environment at /var/chroot
  - A custom shell for SSH forwarding
  - A parsed list of destinations
  - SSH key fingerprints for those destinations
EOF
            exit 0
            ;;

        *)
            printf "Invalid argument: %s\n" "$1"
            exit 1
            ;;
    esac
done


setup-chroot-dir() {

    printf "Setting up directory structure.\n"

    # sudo mkdir -p ${CHROOT_DIR}/{bin,lib,dev,etc,home,usr/bin,lib/x86_64-linux-gnu} || {
    #     err; printf >&2 "Failed to create directory tree for chroot jail!\n"
    # }

    for dir in "${SYSTEM_DIRS[@]}"; do
        if ! [[ -d ${CHROOT_DIR}/$dir ]]; then
            sudo mkdir -p "${CHROOT_DIR}/$dir" || {
                err; printf >&2 "Failed to create directory tree for chroot jail!\n" && return 1
            }
        else
            debug "Directory already exists, skipping: $dir"
        fi
    done

    printf "Copying system files.\n"

    for sysfile in "${SYSTEM_FILES[@]}"; do
        printf "Copying system file: %s\n" "$sysfile"

        if [[ ! -d  "${CHROOT_DIR}$(dirname "$sysfile")" ]]; then
            printf "Creating directory for %s at %s\n" "$sysfile" "$CHROOT_DIR/$(basename "$sysfile")"
            sudo mkdir -p "$(dirname "$sysfile")" || {
                err;
                printf >&2 "Failed to make directory for %s at %s\n" "$sysfile" "$(dirname "$sysfile")"
            }
        fi

        printf "Copying system file %s to %s\n" "$sysfile" "${CHROOT_DIR}$sysfile"
        sudo cp "$sysfile" "${CHROOT_DIR}${sysfile}"

    done

    # Copy over binaries and their linked libraries
    for binary in "${BINARIES[@]}"; do
        debug "Copying binary: ${binary}"
        BIN_PATH=$(which "$binary")
        sudo cp "$BIN_PATH" "${CHROOT_DIR}${BIN_PATH}" || {
            err; printf >&2 "Failed to copy binary '%s' to destination: %s\n" "$binary" "${CHROOT_DIR}${BIN_PATH}"
        }

        # Gather Link Libraries for the binary
        local -a BIN_LLIBS
        IFS=$'\n' read -r -d '' -a BIN_LLIBS < <(ldd "$BIN_PATH" | grep -o '/[^ ]*' )
            # perl -ne 'print "$1\n" if s/^[^\/]*(\/.*)\s*\(.*$/\1/')

        for LLIB in "${BIN_LLIBS[@]}"; do
            debug "LLIB for $binary - ${LLIB}"
            if ! stat "${CHROOT_DIR}${LLIB}" > /dev/null 2>&1; then
                sudo cp "${LLIB}" "${CHROOT_DIR}${LLIB}" || {
                    err; printf >&2 "Failed to copy linked library '%s' to destination: %s" \
                        "$LLIB" \
                        "${CHROOT_DIR}${LLIB}"
                }
            else
                printf "Linked library exists in destination: %s. Skipping.\n" \
                    "${CHROOT_DIR}${LLIB}"
            fi
        done

    done

    # Create special files
    printf "Making character special files.\n"
    for special_file in "${CHAR_SPECIAL_FILES[@]}"; do
        if [[ ! -c "${CHROOT_DIR}${special_file}" ]]; then
            local -a MAJOR_MINOR=()

            read -r -d '' -a MAJOR_MINOR < <(
                awk '/Device type/ {printf "%s\n", $(NF)}' < <(stat "$special_file") | tr ',' ' '
            )

            debug "$special_file - Major: ${MAJOR_MINOR[0]}, Minor: ${MAJOR_MINOR[1]}"

            sudo mknod -m 666 "${CHROOT_DIR}${special_file}" c "${MAJOR_MINOR[@]}" || { 
                err; printf >&2 "Failed to create character special file: %s\n" "${special_file}";
            }

        else
            debug "Character special file already exists: ${CHROOT_DIR}${special_file}"
        fi
    done

    # Copy name switch service files for network functionality
    printf "Copying Name Switch Service (NSS) files.\n"
    sudo cp -r /lib/x86_64-linux-gnu/*nss* "$CHROOT_DIR/lib/x86_64-linux-gnu" || {
        err; printf >&2 "Failed to copy name switch service files!\n"
    }

}

setup-jailed-user() {
    local PASSWORD=

    if [[ $(hostname -I | awk '{print $1}' | tr -d ' ') != "$BASTION_HOST_IP" ]]; then
        err; printf >&2 "Your localhost is not the targeted bastion host.\n" 
    fi

    sudo useradd -m "${JAILED_USER}" || {
        err; printf >&2 "Failed to add jailed user account!\n" 
        return 1
    }

    printf "User account %s succussfully added.\n" "$JAILED_USER"
    read -r -s -p "Enter password for user account: " PASSWORD || {
        err; printf >&2 "Failed to read password for user: %s\n" "$JAILED_USER"
    }

    printf "Setting password for user: %s\n" "${JAILED_USER}"
    printf "%s\n%s\n" "$PASSWORD" "$PASSWORD" | sudo passwd "${JAILED_USER}" || {
        err; printf >&2 "Failed to set password for user: %s\n" "$JAILED_USER" 
        return 1
    }
}

configure-user-shell(){

    if ! [[ -f "./${BASTION_SCRIPT}" ]]; then
        err; printf >&2 "There's no bastion script to copy in the current directory!\n" && return 1
    else
        sudo cp "./$BASTION_SCRIPT" "${CHROOT_DIR}/bin/${BASTION_SCRIPT}" || {
            err;printf >&2 "Failed to copy %s to %s/bin/%s" "$BASTION_SCRIPT" "$CHROOT_DIR" "$BASTION_SCRIPT"
            return 1
        }
        debug "Successfully copied ${BASTION_SCRIPT} to ${CHROOT_DIR}/bin/${BASTION_SCRIPT}."

        sudo perl -pi -e "s,/bin/(?:ba)?sh,/bin/bastion.sh, if m/$JAILED_USER/" /etc/passwd || {
            printf >&2 "Failed to replace default shell in /etc/passwd!\n"
        }

        debug "Jailed user entry in /etc/passwd: $(grep "$JAILED_USER" /etc/passwd)"
        debug "Successfully added ${BASTION_SCRIPT} as shell for ${JAILED_USER}."
    fi
    return 0

}

configure-ssh(){

    # Set up the bastion script and rules for the jailed user
    if ! grep -qi "Match User ${JAILED_USER}" /etc/ssh/sshd_config; then
        {
	    cat <<- EOF | sudo tee -a /etc/ssh/sshd_config > /dev/null 2>&1
		Match User $JAILED_USER
		    ChrootDirectory $CHROOT_DIR
		    PasswordAuthentication yes
		    AuthenticationMethods password
		EOF
        } || {
            err; printf >&2 "Failed to add entry for user in /etc/ssh/sshd_config!\n" 
            return 1
        }
        printf "Added ChrootDirectory rule for %s\n" "$JAILED_USER"
    else
        printf "Entry already found in /etc/ssh/sshd_config. Skipping.\n"
    fi

    printf "Restarting SSH daemon...\n"

    sudo systemctl restart ssh || {
        err; printf >&2 "Failed to restart SSH!\n"
        return 1
    }
    printf "\033[32mSuccessfully restarted SSH!\033[0m\n"

}

parse-ssh-file() {
    if [[ -f $SSH_CONFIG_FILE && -f ./generate-destinations ]]; then
        ./generate-destinations -f "$SSH_CONFIG_FILE" -o "$DESTINATIONS_OUTPUT_FILE" || {
            printf >&2 "Error in destination generation script!\n" && return 1
        }
    else
        printf >&2 "No SSH file to parse for destinations!\n" && return 1
    fi
}

add-ssh-fingerprints() {
    [[ ! -f $DESTINATIONS_OUTPUT_FILE ]] && printf "No parsed SSH file found.\n" && return 1
    set -o pipefail
    local known_hosts="$CHROOT_DIR/etc/ssh/ssh_known_hosts"
    local -a destination_entries
    mapfile -t destination_entries < "$DESTINATIONS_OUTPUT_FILE"
    sudo touch "$known_hosts"
    for entry in "${destination_entries[@]}"; do
        [[ -z $entry ]] && continue
        debug "Attempting to add ${entry##*@} to $known_hosts"
        ssh-keyscan "${entry##*@}" | sudo tee -a "$known_hosts" || {
            printf >&2 "Failed to add fingerprint for %s to %s\n" "${entry##*@}" "$known_hosts"
            printf "Removing entry from destination file: %s\n" "${DESTINATIONS_OUTPUT_FILE}"
            # sudo perl -pi -e "s/^.*$// if m/${entry##*@}/" "$DESTINATIONS_OUTPUT_FILE"
            sudo perl -ni -e "print $1 if not m/${entry##*@}/" "$DESTINATIONS_OUTPUT_FILE"
        }
    done
    set +o pipefail
    return 0
}


# User account setup
printf "Attempting to set up a user account for jailed user: %s\n" "$JAILED_USER"
setup-jailed-user || {
    err; printf >&2 "Failed to set up jailed user!\n" && exit 1
}
printf "\033[32mSuccessfully set up jailed user: %s\033[0m\n" "$JAILED_USER"

# Directory setup
printf "Setting up chroot jail environment in: %s\n" "$CHROOT_DIR"
setup-chroot-dir || {
    err; printf >&2 "Failed to set up chroot directory!\n"; 
    exit 1
}
printf "\033[32mSuccessfully set up chroot directory in %s\033[0m\n" "$CHROOT_DIR"

# User shell setup
printf "Attempting to configure user's shell...\n"
configure-user-shell || {
    err;printf >&2 "Failed to set up user's shell to %s\n" "$BASTION_SCRIPT"
}
printf "\033[32mSuccessfully set up user's shell!\033[0m\n"

# SSH configuration
printf "Attempting to configure SSH rules for jailed user.\n"
configure-ssh || {
    err; printf >&2 "Failed to configure ssh rules for jailed user!\n"; exit 1;
}
printf "\033[32mSuccessfully set up jailed user.\033[0m\n"

printf "Attempting to generate destinations based on SSH config.\n"
parse-ssh-file || {
    err; printf >&2 "Failed to parse ssh file.\n"; exit 1;
}
printf "\033[32mSuccessfully generated destinations file at: %s\033[0m\n" "$DESTINATIONS_OUTPUT_FILE"


printf "Attempting to add SSH fingerprints for destinations...\n"
add-ssh-fingerprints || {
    err; printf >&2 "Failed to add SSH fingerprints for destinations!\n";
}


