#!/bin/bash

for file in "${@}"; do
    printf "Changing quotes in file: %s\n" "$file"
    sed -i  -e "s/’/'/g" -e 's/“/"/g' -e 's/”/"/g' "$file" || {
        printf "Failed to reformat quotes in file: %s\n" "$file"
    }
done

